### ISSUE TITLE
Is androidX supported?

### ISSUE THREAD

**Issue by tzh-goon** [erluxman/pdf_flutter#2]

**Comment by erluxman** [comment]
I am using it on androidX enabled Project, if that is what you mean.

**Comment by erluxman** [comment]
Close it if your question is answered.

**Comment by tzh-goon** [comment]
When androidx is mixed with 'com.android.support.*'，It always comes with errors.

run './gradlew :app:dependencies' in shell,
and you will see:

+--- com.github.barteksc:android-pdf-viewer:3.2.0-beta.1
|    +--- com.github.barteksc:pdfium-android:1.9.0
|    |    \--- com.android.support:support-v4:26.1.0
...

**Comment by erluxman** [comment]
Will look into it.. and get back to you.

**Comment by tzh-goon** [comment]
waiting for the good news from you.

**Comment by erluxman** [comment]
As of right now, there is nothing I can do as I depend on com.github.barteksc:android-pdf-viewer and they haven't migrated yet. If that doesn't happen soon.. I will fork the library and make a jetpack supported one(which is not a recommended way). 

Can you explain to me the issue you are facing? because I am using it in a Jetpack enabled project. I could may be help you out?
